name: STRUKT System CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run lint
      run: npm run lint || echo "No lint script found, skipping..."
      
    - name: Run unit tests
      run: node src/tests/unit.test.js
      
    - name: Run Supabase smoke tests
      run: npm run test:supabase-smoke
      
    - name: Run schema verification (without credentials)
      run: npm run test:schema-verify || echo "⚠️ Schema verification completed with warnings (expected without credentials)"
      continue-on-error: true
      
    - name: Test server startup
      run: |
        echo "🔍 Testing server startup..."
        timeout 10s npm start &
        sleep 5
        curl -f http://localhost:4000/health || (echo "❌ Health check failed" && exit 1)
        echo "✅ Server startup test passed"
      
    - name: Validate Airtable Schema (Legacy)
      run: |
        echo "🔍 Running Airtable schema validation..."
        node scripts/validate_airtable_schema.mjs || echo "⚠️ Airtable validation completed with warnings (non-blocking)"
        echo "✅ Airtable validation step completed"
      continue-on-error: true
      env:
        VALIDATE_AIRTABLE: ${{ secrets.VALIDATE_AIRTABLE }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        
    - name: Supabase integration tests (with credentials)
      run: |
        echo "🔍 Testing Supabase integration..."
        if [ -z "$SUPABASE_URL" ] || [ -z "$SUPABASE_SERVICE_ROLE_KEY" ]; then
          echo "⚠️ Supabase credentials not configured, skipping integration tests"
          exit 0
        fi
        npm run test:schema-verify
        echo "✅ Supabase integration tests passed"
      continue-on-error: true
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}