name: Expo SDK 53 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check Expo installation
      run: npx expo install --check
      
    - name: Run lint
      run: npm run lint || echo "No lint script found, skipping..."
      
    - name: Verify Expo config
      run: |
        if [ -f app.json ]; then
          echo "Expo config found"
          # Check that platforms only contains ios and android
          if grep -q '"web"' app.json; then
            echo "ERROR: Web platform found in Expo config"
            exit 1
          fi
          echo "✅ Expo config is correct (iOS/Android only)"
        fi
      
    - name: Validate Airtable Schema
      run: |
        echo "🔍 Running Airtable schema validation..."
        node scripts/validate_airtable_schema.mjs || echo "⚠️ Airtable validation completed with warnings (non-blocking)"
        echo "✅ Airtable validation step completed"
      continue-on-error: true
      env:
        # Note: Running in dry-run mode by default (no credentials)
        # Set VALIDATE_AIRTABLE=1 in repository secrets to force live validation
        VALIDATE_AIRTABLE: ${{ secrets.VALIDATE_AIRTABLE }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}